### ISSUE TITLE
Relative path problem?

### ISSUE THREAD

**Issue by sacdallago** [ramanathanlab/genslm#77]
**Describe the bug**
Tokenizer file missing. Maybe install not picking up relative paths? Trace:

```
user$ python test.py 
Traceback (most recent call last):
  File "/raid/cdallago/experiments/20221221_genslms/scripts/test.py", line 6, in <module>
    model = GenSLM("genslm_2.5B_patric", model_cache_dir="/home/cdallago/share/experiments/20221221_genslms/models/patric_2_5B")
  File "/home/cdallago/miniconda3/envs/genslms/lib/python3.9/site-packages/genslm/inference.py", line 73, in __init__
    self._tokenizer = self.configure_tokenizer()
  File "/home/cdallago/miniconda3/envs/genslms/lib/python3.9/site-packages/genslm/inference.py", line 102, in configure_tokenizer
    tokenizer_object=Tokenizer.from_file(self.model_info["tokenizer"])
Exception: No such file or directory (os error 2)
```

**To Reproduce**
1. Created fresh python 3.9 conda env
2. Cloned git repo + `pip instal .` from source
3. Downloaded globus 2.5B model weights (actually, a note on this: any suggestion on how to do this on a headless node?)
4. Copied inference example script and adapted weight location:
```python
import torch
import numpy as np
from torch.utils.data import DataLoader
from genslm import GenSLM, SequenceDataset

model = GenSLM("genslm_2.5B_patric", model_cache_dir="/home/cdallago/share/experiments/20221221_genslms/models/patric_2_5B")
model.eval()

# Input data is a list of gene sequences
sequences = [
    "ATGAAAGTAACCGTTGTTGGAGCAGGTGCAGTTGGTGCAAGTTGCGCAGAATATATTGCA",
    "ATTAAAGATTTCGCATCTGAAGTTGTTTTGTTAGACATTAAAGAAGGTTATGCCGAAGGT",
]

dataset = SequenceDataset(sequences, model.seq_length, model.tokenizer)
dataloader = DataLoader(dataset)

# Compute averaged-embeddings for each input sequence
embeddings = []
with torch.no_grad():
    for batch in dataloader:
        outputs = model(
            batch["input_ids"], batch["attention_mask"], output_hidden_states=True
        )
        # outputs.hidden_states shape: (layers, batch_size, sequence_length, hidden_size)
        emb = outputs.hidden_states[0].detach().cpu().numpy()
        # Compute average over sequence length
        emb = np.mean(emb, axis=1)
        embeddings.append(emb)

# Concatenate embeddings into an array of shape (num_sequences, hidden_size)
embeddings = np.concatenate(embeddings)
embeddings.shape
```

5. Run `python test.py`

**Expected behavior**
Get some output on STDOUT (and not STDERR :D)

**Environment (please complete the following information):**
Run on a V100 DGX station running Ubuntu, basically

**Additional info**:
model dir is populated
```
user$ ls /home/cdallago/share/experiments/20221221_genslms/models/patric_2_5B
patric_2.5b_epoch00_val_los_0.29_bias_removed.pt
```

**Comment by sacdallago** [comment]
I re-installed using the pip `-e` option and this seems to have done the trick.

I.e.: `pip install -e .` from the cloned repo
